---
subfamily:
  - Family: Cardinalfishes
  - Family: Pufferfishes
  - Family: Morays
  - Family: Scorpionfishes
  - Family: Jacks
  - Family: Wrasses
subclass:
  - Class: Sea Anemones and Corals
suborder:
  - Order: Octopuses
superorder:
  - Class: Sea Stars
  - Infraclass: Sharks
  - Infraclass: Euthyneuran Gastropods
superfamily:
  - Subclass: Caenogastropods
  - Infraclass: Euthyneuran Gastropods
  - Order: Nudibranchs
  - Order: Octopuses
  - Order: Scallops and Allies
  - Suborder: Prawns
  - Infraorder: True Crabs
family:
  - Superorder: Squids and Cuttlefishes
  - Order: Flatfishes
  - Order: True Eels
  - Order: Nudibranchs
  - Suborder: Prawns
  - Class: Sea Stars
  - Subclass: Mantis Shrimps
  - Subclass: Sedentary and Tube-dwelling Bristleworms
  - Subclass: Caenogastropods
  - Superfamily: Hermit Crabs
infraclass:
  - Class: Bivalves
  - Subclass: sea urchins
order:
  - Class: Sea Anemones and Corals
  - Class: "Sea Urchins, Sand Dollars, and Heart Urchins"
  - Class: Sea Stars
  - Class: Brittle Stars
  - Class: Bivalves
  - Infraclass: Sharks
  - Infraclass: Rays
  - Infraclass: Euthyneuran Gastropods
  - Superorder: Squids and Cuttlefishes
genus:
  - Subfamily: Damselfishes
  - Subfamily: Groupers

